# Generated by Django 4.2.3 on 2024-06-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='date',
        ),
        migrations.AddField(
            model_name='usage',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usage',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usage',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
